name: Github Pages

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
        types:
            - closed
    push:
        branches:
            - main

jobs:
    deploy:
        if: ${{ github.event.pull_request.merged }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'
            - name: Prepare venv
              run: |
                python3.10 -m venv venv
            - name: Install dependencies
              run: |
                source venv/bin/activate && pip install -e .[docs]
            - name: Deploy docs
              run: |
                git pull && venv/bin/python -m mkdocs gh-deploy
